databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn new_hall.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: postgresql://postgres:bugattis@localhost:5432/new_hall
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4