databases:
  - name: new-halldb
    plan: free
    databaseName: new-hall
    user: new-hall

services:
  - type: web
    plan: free
    name: new-hall
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn new-hall.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: new-halldb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4